/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Uknown
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbAltaM = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbBajaM = new javax.swing.JButton();
        jbModifiacionM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbAltaA = new javax.swing.JButton();
        jbBajaA = new javax.swing.JButton();
        jbModifiacionA = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbAsistencia = new javax.swing.JButton();
        jbPagos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE CONTROL DE ACADEMIAS IYF TOLUCA");

        jbAltaM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAltaM.setText("ALTA");
        jbAltaM.setActionCommand("");
        jbAltaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaMActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ACTUALIZACION / REGISTRO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("MAESTROS");

        jbBajaM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbBajaM.setText("BAJA");
        jbBajaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaMActionPerformed(evt);
            }
        });

        jbModifiacionM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbModifiacionM.setText("MODIFIACION");
        jbModifiacionM.setActionCommand("");
        jbModifiacionM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifiacionMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("ALUMNOS");

        jbAltaA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAltaA.setText("ALTA");
        jbAltaA.setActionCommand("");
        jbAltaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaAActionPerformed(evt);
            }
        });

        jbBajaA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbBajaA.setText("BAJA");
        jbBajaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaAActionPerformed(evt);
            }
        });

        jbModifiacionA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbModifiacionA.setText("MODIFIACION");
        jbModifiacionA.setActionCommand("");
        jbModifiacionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifiacionAActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("ASISTENCIA / PAGOS");

        jbAsistencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAsistencia.setText("ASISTENCIA");
        jbAsistencia.setActionCommand("");
        jbAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsistenciaActionPerformed(evt);
            }
        });

        jbPagos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbPagos.setText("PAGOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAltaM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBajaM, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbModifiacionM))
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbAltaA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbBajaA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbModifiacionA))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAltaM)
                    .addComponent(jbBajaM)
                    .addComponent(jbModifiacionM))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAltaA)
                    .addComponent(jbBajaA)
                    .addComponent(jbModifiacionA))
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAsistencia)
                    .addComponent(jbPagos))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaAActionPerformed
        Alta_Alumno al=new Alta_Alumno();
        
        this.dispose();
        al.setVisible(true);
    }//GEN-LAST:event_jbAltaAActionPerformed

    private void jbAltaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaMActionPerformed
        this.dispose();
        
        new Alta_Maestro().setVisible(true);
    }//GEN-LAST:event_jbAltaMActionPerformed

    private void jbBajaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaAActionPerformed
        this.dispose();
        
        new Baja_Alumno().setVisible(true);
    }//GEN-LAST:event_jbBajaAActionPerformed

    private void jbBajaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaMActionPerformed
        JOptionPane.showMessageDialog(null, "Opcion no disponible por el momento");
    }//GEN-LAST:event_jbBajaMActionPerformed

    private void jbModifiacionMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifiacionMActionPerformed
        JOptionPane.showMessageDialog(null, "Opcion no disponible por el momento");
    }//GEN-LAST:event_jbModifiacionMActionPerformed

    private void jbModifiacionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifiacionAActionPerformed
        JOptionPane.showMessageDialog(null, "Opcion no disponible por el momento");
    }//GEN-LAST:event_jbModifiacionAActionPerformed

    private void jbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsistenciaActionPerformed
        this.dispose();
        new Asistencia().setVisible(true);
    }//GEN-LAST:event_jbAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAltaA;
    private javax.swing.JButton jbAltaM;
    private javax.swing.JButton jbAsistencia;
    private javax.swing.JButton jbBajaA;
    private javax.swing.JButton jbBajaM;
    private javax.swing.JButton jbModifiacionA;
    private javax.swing.JButton jbModifiacionM;
    private javax.swing.JButton jbPagos;
    // End of variables declaration//GEN-END:variables
}
